// <auto-generated />
using System;
using AzureStorageBackup.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzureStorageBackup.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AzureStorageBackup.Api.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlobEndpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProxyHost")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProxyMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProxyPassword")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProxyPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProxyUsername")
                        .HasColumnType("TEXT");

                    b.Property<int>("Region")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseProxy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AzureStorageBackup.Api.Models.BackupConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataTier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DontCompressRules")
                        .HasColumnType("TEXT");

                    b.Property<string>("DontGroupRules")
                        .HasColumnType("TEXT");

                    b.Property<long>("GroupCapBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IgnoreRules")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeSymlinks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndexTier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalRoot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAgeDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxVersions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionMode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SingleFileThresholdBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VerboseLogging")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("VolumeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BackupConfigs");
                });

            modelBuilder.Entity("AzureStorageBackup.Api.Models.CachedVersionIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("IdentityTicks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Container", "Version")
                        .IsUnique();

                    b.ToTable("CachedVersionIndexes");
                });

            modelBuilder.Entity("AzureStorageBackup.Api.Models.GlobalSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeadWeightThresholdPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultDataTier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultDontCompressRules")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultDontGroupRules")
                        .HasColumnType("TEXT");

                    b.Property<long>("DefaultGroupCapBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultIgnoreRules")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DefaultIncludeSymlinks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultIndexTier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultMaxAgeDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultMaxVersions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultRetentionMode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DefaultSingleFileThresholdBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DefaultVerboseLogging")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DefaultVolumeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DownloadConcurrency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogEphemeralMaxAgeDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RepackDownloadArchive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RepackDownloadCold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RepackDownloadCool")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RepackDownloadHot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RetryBackoffSeconds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryMaxTotalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UploadConcurrency")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GlobalSettings");
                });

            modelBuilder.Entity("AzureStorageBackup.Api.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("AzureStorageBackup.Api.Models.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("AzureStorageBackup.Api.Models.LocalBackupState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("InfoBytes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Container")
                        .IsUnique();

                    b.ToTable("LocalBackupStates");
                });

            modelBuilder.Entity("AzureStorageBackup.Api.Models.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ephemeral")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("AzureStorageBackup.Api.Models.NotificationConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Events")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProxyUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationConfigs");
                });

            modelBuilder.Entity("AzureStorageBackup.Api.Models.ScheduledTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckCloudLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckLocalLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CheckRehydrateTier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScheduledTasks");
                });

            modelBuilder.Entity("AzureStorageBackup.Api.Models.GroupMember", b =>
                {
                    b.HasOne("AzureStorageBackup.Api.Models.Group", null)
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AzureStorageBackup.Api.Models.Group", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
