namespace AzureStorageBackup.Api.Services;

/// <summary>
/// The boundary rule set of a backup's scope (design docs/configuration.md). Each rule is one
/// "path → include/exclude"; the decision comes from the **longest matching prefix**; no match at all means include (the root's implicit default).
/// <para>
/// Deliberately **not shared** with <see cref="IgnoreRuleSet"/>: that one is glob matching + last rule wins,
/// this one is exact paths + longest prefix wins. Mixing them would only make both sides more complex.
/// </para>
/// <para>
/// Two write invariants (maintained jointly by <see cref="With"/> and <see cref="Parse"/>), which is why the rule set
/// stays minimal forever and never grows out of control:
/// 1) Every rule's decision must be the **opposite** of its nearest ancestor rule — the same decision is redundant and is not persisted;
/// 2) When writing a rule, delete every deeper rule that has it as a strict prefix — they are already covered.
/// </para>
/// <para>
/// A corollary of invariant 1 is that the tri-state display can be computed **without loading any child nodes** (see
/// <see cref="IsPartial"/>), which is exactly why lazy loading and tri-state can hold at the same time.
/// </para>
/// </summary>
public sealed class ScopeRuleSet
{
    // In Ordinal order an ancestor always sorts before its descendants (a strict prefix is always less than its extensions), so normalization needs only a single ordered pass.
    private readonly SortedDictionary<string, bool> _rules;

    private ScopeRuleSet(SortedDictionary<string, bool> rules) => _rules = rules;

    private static SortedDictionary<string, bool> Empty() => new(StringComparer.Ordinal);

    /// <summary>Empty rule set: include everything. This is the default when no scope has been configured.</summary>
    public static ScopeRuleSet All { get; } = new(Empty());

    /// <summary>Whether this is "include everything" (no rules at all).</summary>
    public bool IsAll => _rules.Count == 0;

    /// <summary>
    /// Parse rule text. null/empty → <see cref="All"/>. Unrecognized lines are **skipped, not thrown on**, matching how
    /// <see cref="IgnoreRuleSet"/> treats blank lines/comments: in theory this text is only ever generated by the UI,
    /// but it lives in the database, and breaking it by hand should not crash the backup outright. Normalize immediately after parsing (clear out redundant rules).
    /// </summary>
    public static ScopeRuleSet Parse(string? text)
    {
        var rules = Empty();
        foreach (var raw in (text ?? "").Split('\n', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries))
        {
            var included = raw[0] switch { '+' => true, '-' => false, _ => (bool?)null };
            if (included is null)
                continue;

            var path = Normalize(raw[1..]);
            // A `..` segment cannot match any real relative path under longest-prefix matching anyway (the paths the scanner
            // hands out never contain one), but keeping it would only make people think it means something. Drop it.
            if (path.Split('/').Any(seg => seg is ".." or "."))
                continue;

            rules[path] = included.Value;
        }

        Normalize(rules);
        return new ScopeRuleSet(rules);
    }

    /// <summary>Whether a path is in scope: longest-prefix match, "include" when nothing matches. O(path depth).</summary>
    public bool IsInScope(string relativePath)
    {
        var path = Normalize(relativePath);
        while (true)
        {
            if (_rules.TryGetValue(path, out var included))
                return included;
            if (path.Length == 0)
                return true; // Not even a root rule → include by default
            var slash = path.LastIndexOf('/');
            path = slash < 0 ? "" : path[..slash];
        }
    }

    /// <summary>
    /// Whether this directory's subtree still holds anything that needs backing up: it is itself in scope, **or** there is a `+` rule with it as a prefix.
    /// <para>
    /// The scanner must use this rather than <see cref="IsInScope"/> to decide whether to descend: an excluded directory
    /// may still have re-included subdirectories beneath it, and judging on IsInScope alone would prune them away too.
    /// </para>
    /// </summary>
    public bool MayContainIncluded(string dirPath)
    {
        if (IsInScope(dirPath))
            return true;

        var under = Under(dirPath);
        foreach (var (key, included) in _rules)
            if (included && IsUnder(key, under))
                return true;

        return false;
    }

    /// <summary>
    /// The "indeterminate" box of the tri-state: the rule set holds a rule with this directory as a strict prefix, which means the subtree disagrees internally.
    /// <para>
    /// This is **one-directional**: with `- docs` + `+ docs/a` + `+ docs/b`, when docs happens to contain only a and b,
    /// the actual effect is fully selected, yet this still reports indeterminate. Without loading the child nodes there is
    /// no way to know whether those two rules exhaust the directory — that is the inherent cost of lazy loading.
    /// Indeterminate is the conservative and honest side: it faithfully reflects "explicit rules are at work here" instead
    /// of mis-reporting "partially selected" as "fully selected". The backup result is unaffected, only the display is.
    /// </para>
    /// </summary>
    public bool IsPartial(string dirPath)
    {
        var under = Under(dirPath);
        foreach (var key in _rules.Keys)
            if (IsUnder(key, under))
                return true;

        return false;
    }

    /// <summary>
    /// Write one rule, maintain both invariants, return a **new instance** (the original is untouched — the mirror
    /// implementation on the frontend is immutable too, since React relies on reference changes to trigger re-renders).
    /// </summary>
    public ScopeRuleSet With(string path, bool included)
    {
        var key = Normalize(path);
        var next = new SortedDictionary<string, bool>(_rules, StringComparer.Ordinal);

        // Invariant 2: clear out the deeper rules this one covers.
        var under = Under(key);
        foreach (var deeper in next.Keys.Where(k => IsUnder(k, under)).ToList())
            next.Remove(deeper);

        // Invariant 1: do not persist if the decision matches the nearest ancestor. Remove our own rule first, and the nearest remaining match is the ancestor's decision.
        next.Remove(key);
        if (new ScopeRuleSet(next).IsInScope(key) != included)
            next[key] = included;

        return new ScopeRuleSet(next);
    }

    /// <summary>Normalized text, one rule per line. Empty rule set → empty string.</summary>
    public override string ToString() =>
        string.Join('\n', _rules.Select(r =>
            r.Key.Length == 0
                ? (r.Value ? "+" : "-")
                : $"{(r.Value ? '+' : '-')} {r.Key}"));

    /// <summary>Strip redundant rules in place (those whose decision matches their nearest ancestor). Ancestors are always
    /// visited before descendants, so one pass suffices: the rule being removed has the same decision as its ancestor, so removing it changes nothing about the ancestor decision any descendant sees.</summary>
    private static void Normalize(SortedDictionary<string, bool> rules)
    {
        foreach (var key in rules.Keys.ToList())
        {
            var self = rules[key];
            rules.Remove(key);
            if (new ScopeRuleSet(rules).IsInScope(key) != self)
                rules[key] = self;
        }
    }

    /// <summary>The prefix shared by every descendant of this directory (empty string for the root, "dir/" otherwise).</summary>
    private static string Under(string dirPath)
    {
        var p = Normalize(dirPath);
        return p.Length == 0 ? "" : p + "/";
    }

    /// <summary>Whether key sits strictly below under (excluding the directory under itself refers to).</summary>
    private static bool IsUnder(string key, string under) =>
        key.Length > under.Length && key.StartsWith(under, StringComparison.Ordinal);

    /// <summary>Normalize a path: backslashes to forward slashes, empty segments dropped (which deals with leading/trailing and repeated slashes in one go).</summary>
    private static string Normalize(string path) =>
        string.Join('/', path.Replace('\\', '/')
            .Split('/', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries));
}
